### PR TITLE
pv/ sub-directories

### PR DESCRIPTION
**Pull request by mdavidsaver**
A demonstration of what I intend with #15.  All header files not currently residing in a directory named 'pv' are moved for their current directory to a sub-directory named 'pv'.  Makefiles and a few #includes in .cpp are adjusted accordingly.

### CODE REVIEW

**Comment by dhickin** [comment]
See comments in #15.

I'll wait until we have a group decision on that before I merge or close it.

**Comment by mdavidsaver** [comment]
@mrkraimer you mentioned this morning that you have made similar changes.  Can you either publish them, or comment on whether they are substantially different from those of this branch?

**Comment by anjohnson** [comment]
@mdavidsaver I suspect Marty was referring to equivalent changes in the exampleCPP and pvDatabaseCPP modules.

**Comment by mrkraimer** [comment]
On 01/26/2016 03:13 PM, mdavidsaver wrote:
>
> @mrkraimer <https://github.com/mrkraimer> you mentioned this morning 
> that you have made similar changes. Can you either publish them, or 
> comment on whether they are substantially different from those of this 
> branch?
>

The two projects were:

1) pvDatabaseCPP - This is now merged into master branch of epics-base
2) exampleCPP - pull request #4 has been created. Check Failed. I will 
look for problem.

**Comment by dhickin** [comment]
Pull request OK, but conflicts after merging #17. Rebased, fixed a commit log typo in the process and pushed. Closing - no need to merge.

**Pull request closed without merging**
